[[clients]]
hostname = "franklaptop.local"
ips = ["192.168.68.114"]
position = "left"
activate_on_startup = true

[authorized_fingerprints]
"c6:42:24:d7:e7:53:f6:80:c6:19:ff:1d:31:59:f8:60:4c:a1:3c:50:41:cc:fb:59:48:0a:0f:4b:e8:61:ec:a4" = "Laptop"
